#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(
    set = 0,
    binding = 0,
    rgba8
) uniform writeonly image2D color_image;

layout(
    set = 1,
    binding = 0,
    r16
) uniform writeonly image2D depth_image;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    imageStore(color_image, coord, vec4(1.0, 1.0, 0.0, 1.0));
    //imageStore(color_image, coord, vec4(0.5, 0.5, 0.5, 1.0));
    imageStore(depth_image, coord, vec4(0.0, 0.0, 0.0, 0.0));  // only x matters, 0 is near plane
}
